FROM python:3.8-buster

USER 0
RUN apt-get -y update
RUN groupadd -g 1000 -r debian && \
  useradd -u 1000 -r -g debian debian

# Copy config files and actions folder to working directory
WORKDIR /app

# By best practices, don't run the code with root user
RUN chgrp -R 1000 /app && chmod -R g=u /app

USER 1000
RUN git clone https://github.com/earroyoh/Dadbot.git

# Install extra requirements for actions code, if necessary (uncomment next line)
WORKDIR /app/Dadbot
RUN python3 -m pip install -t /app/.local --upgrade pip && \
    python3 -m pip install -t /app/.local --upgrade --no-cache-dir -r requirements.txt
ENV PATH "/app/.local/bin:/bin:/usr/bin:/usr/local/bin"
ENV PYTHONPATH "/app/.local/:/opt/venv/:/usr/local/"

EXPOSE 5005
CMD ["python3", "-m", "rasa", "run", "-m", "models", "--enable-api", "--cors", "'*'", "--connector", "voice_connector.ChatInput", "--debug"]
