FROM nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04

# To install system dependencies
ENV TZ="Europe/Madrid" 
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update -y -qq && \
    apt-get install -y apt-utils software-properties-common && \
    apt-get install -y git gcc curl nano gnupg python3-pip python3-wheel libsndfile1 portaudio19-dev
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN python3 -m pip install --upgrade --no-cache-dir pip

WORKDIR /app
RUN useradd -u 1000 debian && \
    chown -Rf 1000:1000 /app && \
    chmod -Rf 755 /app

USER 1000
RUN git clone https://github.com/earroyoh/Dadbot.git

## NVIDIA modules for speech synthesis
ENV PATH "/app/.local/bin:/usr/local/cuda-11.2/bin:/opt/venv/bin:/bin:/usr/bin:/usr/local/bin"
ENV PYTHONPATH "/app/.local/:/opt/venv/:/usr/local/"
ENV CUDA_INC_DIR "/usr/local/cuda-10.2/targets/x86_64-linux/include"
RUN git clone https://github.com/NVIDIA/DeepLearningExamples.git && \
    git clone https://github.com/NVIDIA/apex.git && \
    python3 -m pip install --upgrade --no-cache-dir -t /app/.local fire scikit-build data pyaudio && \
    python3 -m pip install --upgrade --no-cache-dir -t /app/.local -r DeepLearningExamples/CUDA-Optimized/FastSpeech/requirements.txt

WORKDIR /app/Dadbot
RUN ln -s ../DeepLearningExamples/CUDA-Optimized/FastSpeech/fastspeech fastspeech && \
    ln -s ../DeepLearningExamples/CUDA-Optimized/FastSpeech/tacotron2 tacotron2 && \
    ln -s ../DeepLearningExamples/CUDA-Optimized/FastSpeech/waveglow waveglow && \
    ln -s ../waveglow tacotron2/waveglow
# Spanish symbols patch
RUN cp symbols.py ../DeepLearningExamples/CUDA-Optimized/FastSpeech/fastspeech/text_norm/
# Glow dependecy 
RUN curl --insecure -o glow.py https://raw.githubusercontent.com/NVIDIA/waveglow/master/glow.py

# rasa installation and pip dependencies
RUN python3 -m pip install --upgrade --no-cache-dir -t /app/.local -r requirements-cuda.txt

EXPOSE 5005
CMD ["python3", "-m", "rasa", "run", "-m", "models", "--enable-api", "--connector", "voice_connector_nvidia.ChatInput", "--ssl-certificate=dadbot.crt", "--ssl-keyfile=dadbot.key", "--debug"]
