# Extend the official Rasa SDK image
FROM rasa/rasa-sdk:2.2.0

USER 0
RUN groupadd -g 1000 -r debian && \
  useradd -u 1000 -r -g debian debian

# Copy config files and actions folder to working directory
WORKDIR /app
COPY actions /app/actions

# By best practices, don't run the code with root user
RUN chgrp -R 1000 /app && chmod -R g=u /app
USER 1000
ENV HOME /app

# Install extra requirements for actions code, if necessary (uncomment next line)
RUN source /opt/venv/bin/activate venv && \
    python3 -m pip install -t /app/.local --upgrade pip && \
    python3 -m pip install -t /app/.local --upgrade --no-cache-dir -r actions/requirements-actions.txt
ENV PATH "/app/.local/bin:/opt/venv/bin:/bin:/usr/bin:/usr/local/bin"
ENV PYTHONPATH "/app/.local/:/opt/venv/:/usr/local/"

EXPOSE 5055
CMD ["start", "--actions", "actions"]
