FROM python:3.8-slim

USER 0
RUN groupadd -g 1000 -r debian && \
  useradd -u 1000 -r -g debian debian

# Copy config files and actions folder to working directory
WORKDIR /app
COPY dadbot.* /app/
COPY manage.py /app
COPY requirements-web.txt /app
COPY rasadjango/ /app/rasadjango/

# By best practices, don't run the code with root user
RUN chgrp -R 1000 /app && chmod -R g=u /app
USER 1000

# Install extra requirements for actions code, if necessary (uncomment next line)
RUN python3 -m pip install -t /app/.local --upgrade pip && \
    python3 -m pip install -t /app/.local --upgrade --no-cache-dir -r requirements-web.txt
ENV PATH "/app/.local/bin:/bin:/usr/bin:/usr/local/bin"
ENV PYTHONPATH "/app/.local/:/opt/venv/:/usr/local/"

EXPOSE 8000
CMD ["python3", "dadbot.py"]
